master_snakefile_prefix = os.path.dirname(os.path.dirname(workflow.snakefile))

# -------- Config files -------- #
configfile: master_snakefile_prefix + "/config/config.yaml"

if os.path.exists("config/config.yaml"):
    configfile: "config/config.yaml"

# --------- Load Rules --------- #
include: "rules/constants.smk"
include: "rules/common.smk"
include: "rules/compute_qv.smk"
include: "rules/filter.smk"
include: "rules/identify_contaminants.smk"
include: "rules/create_filtered_fastq.smk"
include: "rules/plots.smk"
include: "rules/overwrite_fastq.smk"

# --------  Begin -------- #
if config["new_fastq"]: # new_fastq = True; prepare overwriting, not actual overwrite
    rule prepare_overwrite:
        input:
            expand(
                "results/overwrite_target_lists/{sample}.overwrite_target_lists.tab.gz",
                sample=df.index.values,
            )
else:
    rule back_ref_qc:
        input:
            get_final_output,

rule overwrite:
    input:
        expand(
            "results/overwrite_records/{sample}.overwrite_records.tab.gz",
            sample=df.index.values,
        )
